# Generated by Django 3.1.4 on 2021-06-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceleafdisease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
