# Generated by Django 3.1.4 on 2021-06-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceleafdisease', '0002_training_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(upload_to='input/'),
        ),
    ]
